const CONFIG = Object.freeze({
  APP_NAME: 'Danh bạ MTTQ tỉnh Cao Bằng',
  VERSION: '1.1.0',
  DB_ID: '1E1pOxwBiQI4GDehXrYYghwULUg6pGZhbILXEOs-vIcY',
  ROOT_ORG_ID: 'ORG_CB_000',
  SHEETS: {
    ORGANIZATIONS: 'ORGANIZATIONS',
    GROUPS: 'GROUPS',
    CONTACTS: 'CONTACTS',
    USERS: 'USERS',
    ROLES: 'ROLES',
    SETTINGS: 'SETTINGS',
    AUDIT: 'AUDIT_LOG',
    IMPORT: 'IMPORT_LOG',
    REVIEW: 'REVIEW_QUEUE',
    REVIEW_REQUESTS: 'REVIEW_REQUESTS',
    BACKUP_LOG: 'BACKUP_LOG'
  },
  AUTH: {
    HASH_ITERATIONS: 6000,
    SESSION_TTL_SECONDS: 21600,
    MIN_PASSWORD_LENGTH: 8
  },
  LIMITS: {
    MAX_AVATAR_BYTES: 2097152,
    MAX_TEXT_LENGTH: 500,
    MAX_NAME_LENGTH: 160,
    MAX_EMAIL_LENGTH: 254
  }
});
